# Generated by Django 4.0.4 on 2022-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='static/Question_mark_(black).svg.png', upload_to='books'),
        ),
    ]
